name: Deploy EquipLocal

on:
  push:
    branches:
      - Equiplocal-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            cd /opt/equiplocal

            git pull origin Equiplocal-Branch

            docker compose down

            docker compose up -d --build

            docker ps
